In [1]:
import shutil as sh
import pandas as pd

# cria diretório para o dataset das fotos renomeadas

!mkdir dataset

mkdir: dataset: File exists

In [2]:
# cria função para copiar um arquivo de foto e renomea-lo de acordo com as colunas da tabela de metadados
# (poderia só sobrescrecer, mas por cautela achei melhor copiar e guardar numa pasta diferente)

def copy_with_new_name(row):
    new_name = f"{row['classe']}_{row['exemplo']}_{row['periodo']}_{row['local']}_{row['fundo']}_{row['repeticao']}.jpg"
    sh.copyfile('original_dataset/' + row['arquivo'] + '.jpg', 'dataset/' + new_name)
    return new_name

In [3]:
# lê o arquivo excel com a tabela de metadados

metadata = pd.read_excel('original_dataset/original_metadata.xlsx')

In [4]:
# aplica a função sobre os arquivos originais de acordo com a coluna 'arquivo'

metadata['arquivo'] = metadata.apply(copy_with_new_name, axis=1)

In [5]:
# cria uma nova tabela excel com os novos nomes de arquivo

metadata.to_excel('./metadata.xlsx', index=False)

In [6]:
data = pd.read_excel('./metadata.xlsx')

In [7]:
data

,arquivo,classe,exemplo,periodo,local,fundo,repeticao
0,chinelo_A_dia_fora_bege_1.jpg,chinelo,A,dia,fora,bege,1
1,chinelo_A_dia_fora_bege_2.jpg,chinelo,A,dia,fora,bege,2
2,chinelo_A_dia_fora_bege_3.jpg,chinelo,A,dia,fora,bege,3
3,chinelo_A_dia_fora_azul_1.jpg,chinelo,A,dia,fora,azul,1
4,chinelo_A_dia_fora_azul_2.jpg,chinelo,A,dia,fora,azul,2
...,...,...,...,...,...,...,...
535,tesoura_C_noite_dentro_laranja_2.jpg,tesoura,C,noite,dentro,laranja,2
536,tesoura_C_noite_dentro_laranja_3.jpg,tesoura,C,noite,dentro,laranja,3
537,tesoura_C_noite_dentro_verde_1.jpg,tesoura,C,noite,dentro,verde,1
538,tesoura_C_noite_dentro_verde_2.jpg,tesoura,C,noite,dentro,verde,2
539,tesoura_C_noite_dentro_verde_3.jpg,tesoura,C,noite,dentro,verde,3